# pylint: skip-file
"""
Django settings for utils_site project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import Csv, config

# Sentry Error Tracking
# Enabled by default in production (DEBUG=False)
# Set SENTRY_DSN="" to disable
SENTRY_DSN = config(
    "SENTRY_DSN",
    default="https://b3fdb00de949875598b3a1e9e5a54de0@o4510504663973888.ingest.de.sentry.io/4510504665940048",
)
if SENTRY_DSN and not config("DEBUG", default=True, cast=bool):
    try:
        import sentry_sdk
        from sentry_sdk.integrations.celery import CeleryIntegration
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.redis import RedisIntegration

        # Filter handled errors - don't send InvalidPDFError as unhandled exceptions
        # These are expected user errors (corrupted files), not bugs
        def before_send(event, hint):
            logentry = event.get("logentry") or {}
            logentry_message = logentry.get("message") or ""
            logentry_params = logentry.get("params") or []
            base_message = event.get("message") or logentry_message
            full_message = (
                (base_message or "") + " " + " ".join(str(p) for p in logentry_params)
            )

            # Don't send InvalidPDFError as exception - it's handled gracefully
            if "exc_info" in hint and hint["exc_info"][0].__name__ == "InvalidPDFError":
                event["level"] = "info"
                event["tags"] = event.get("tags", {})
                event["tags"]["error_type"] = "handled"
                event["tags"]["user_error"] = "true"

            # Drop Gunicorn access logs - these are just successful HTTP requests, not errors
            if event.get("logger") == "gunicorn.access":
                return None

            # Drop any logs with WSGI parameters (detailed access logs)
            if "message.parameter." in full_message or "{wsgi" in full_message:
                return None

            # Drop logs with access log format patterns
            if any(
                pattern in full_message
                for pattern in ["%(h)s", "%(l)s", "%(u)s", "%(t)s", "%(r)s"]
            ):
                return None

            # Drop health check logs specifically
            if "/health/" in full_message or "GET /health/" in full_message:
                return None

            # Drop noisy CSRF warnings caused by bots, broken clients, and cached pages
            # These are common when:
            # - Bots try to submit forms without valid CSRF tokens
            # - Users submit forms from cached pages with expired CSRF tokens
            # - Session/Cookie issues (especially with Cloudflare or CDN)
            if event.get("logger") == "django.security.csrf":
                if "Referer checking failed" in full_message:
                    return None
                # Filter "CSRF token from POST incorrect" - usually from cached pages or bots
                if "CSRF token from POST incorrect" in full_message:
                    return None

            # Filter naive datetime warnings - these are handled by improved _dt_from_timestamp
            # but may still occur from legacy data or external API responses
            if event.get("logger") == "py.warnings":
                if (
                    "RuntimeWarning" in full_message
                    and "naive datetime" in full_message
                ):
                    if (
                        "subscription_end_date" in full_message
                        or "DateTimeField" in full_message
                    ):
                        return None

            # Drop DisallowedHost errors - these are just bot scanners
            # Should be blocked by FilterProxyRequestsMiddleware, but catch any that slip through
            if "exc_info" in hint:
                exc_type = hint["exc_info"][0]
                if exc_type and exc_type.__name__ == "DisallowedHost":
                    return None
            if (
                "DisallowedHost" in full_message
                or "Invalid HTTP_HOST header" in full_message
            ):
                return None

            # Drop noisy Gunicorn error logs (invalid protocol / php probes / bot scanners)
            if event.get("logger") == "gunicorn.error":
                # Examples: "Invalid HTTP request line: 'SSH-2.0-Go'", "Error handling request /admin/config.php"
                # Bot scanners look for: .php, .asp, .aspx, .env, .git, wp-admin, etc.
                bot_patterns = [
                    ".php",
                    ".asp",
                    ".aspx",
                    ".env",
                    ".git",
                    "wp-admin",
                    "wp-login",
                    "wp-content",
                    "wordpress",
                    "xmlrpc",
                    "phpmyadmin",
                    "config.php",
                    "admin.php",
                    "Invalid HTTP request line",
                    "SSH-2.0",
                    "DisallowedHost",  # Host header attacks
                    "mstshash",  # RDP scanner
                ]
                if any(pattern in full_message for pattern in bot_patterns):
                    return None

                # Absolute-form requests and random host:port probes (noise)
                if "http://" in full_message or "https://" in full_message:
                    return None
                if ":443" in full_message or ":80" in full_message:
                    return None

            # Drop health-check events (e.g. /health/) so they don't clutter Sentry
            request_data = event.get("request", {}) or {}
            url = request_data.get("url", "") or ""
            if "/health" in url:
                return None

            # Drop celery-beat INFO logs (e.g. "beat: Starting...")
            # These are normal operational logs, not errors
            if event.get("logger") == "celery.beat" and event.get("level") == "info":
                return None

            # Drop Celery INFO logs in general to reduce noise
            # We only care about warnings and errors
            if (
                event.get("logger", "").startswith("celery.")
                and event.get("level") == "info"
            ):
                return None

            # Drop WorkerLostError from task cancellation
            # These are expected when users cancel tasks (close page/tab)
            # We use SIGTERM for graceful cancellation
            if "exc_info" in hint:
                exc_type = hint["exc_info"][0]
                if exc_type and exc_type.__name__ == "WorkerLostError":
                    # Check if this is from user cancellation (SIGTERM)
                    exc_value = str(hint["exc_info"][1])
                    if "SIGTERM" in exc_value or "signal 15" in exc_value:
                        # User cancelled - don't send to Sentry
                        return None
                    # SIGKILL (signal 9) might be OOM killer - keep those errors
                    # They indicate memory issues that need attention

            return event

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                CeleryIntegration(),
                RedisIntegration(),
            ],
            # Send user info (IP, etc.) for debugging
            send_default_pii=True,
            # Enable sending logs to Sentry (only ERROR and above to avoid spam)
            enable_logs=True,
            # Capture 10% of transactions for performance monitoring (free plan)
            # Don't use 1.0 - it will exceed free plan limits quickly
            traces_sample_rate=0.1,
            # Environment tag
            environment=config("SENTRY_ENVIRONMENT", default="production"),
            # Release version - update on each release
            release=config("SENTRY_RELEASE", default="convertica@dev"),
            # Filter handled errors
            before_send=before_send,
            # Async transport (non-blocking)
            transport=sentry_sdk.transport.HttpTransport,
            # Max breadcrumbs (events leading to error)
            max_breadcrumbs=50,
            # Note: Profiling (profile_session_sample_rate) is a paid feature
            # Only enable if you upgrade to a paid plan
        )
    except ImportError:
        # sentry-sdk not installed - skip Sentry initialization
        # This allows the app to run without Sentry in development
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable - REQUIRED in production
_default_secret_key = (
    "django-insecure-dev-only-key-do-not-use-in-production-abc123"
    if config("DEBUG", default=True, cast=bool)
    else ""
)
SECRET_KEY = config("SECRET_KEY", default=_default_secret_key)

# Fail fast if SECRET_KEY is not set in production
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable is required in production! "
        'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

# Comma-separated list of allowed hosts
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())

# Site URL for OAuth redirects (falls back to localhost for development)
SITE_URL = config("SITE_URL", default="http://localhost:8003")

# SSL/HTTPS settings for production behind reverse proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    # Django Allauth for social authentication
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    # Note: hCaptcha is used via JavaScript widget and direct API calls, not as Django app
    "src.frontend",
    "src.blog",
    "src.users",
]

# Optional apps (graceful degradation if not installed)
try:
    import django_ratelimit

    INSTALLED_APPS.append("django_ratelimit")
except ImportError:
    pass

try:
    import channels

    INSTALLED_APPS.insert(0, "daphne")  # Daphne must be first for ASGI
    INSTALLED_APPS.append("channels")
except ImportError:
    pass


MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",  # Compress responses (HTML, JSON, CSS, JS) - must be first
    "src.api.middleware.FilterProxyRequestsMiddleware",  # Filter invalid hosts/proxy CONNECT - BEFORE SecurityMiddleware!
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise for static files (if enabled via USE_WHITENOISE env var)
    # Uncomment or use environment variable to enable
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    "src.frontend.admin_protection.AdminIPWhitelistMiddleware",  # Admin IP protection (must be early)
    "src.frontend.middleware.DoubleLanguagePrefixMiddleware",  # Redirect URLs with double language prefixes (must be early)
    "src.api.middleware.RateLimitMiddleware",  # Rate limiting for API
    "src.api.middleware.PerformanceMonitoringMiddleware",  # Performance monitoring
    "src.api.middleware.CSPNonceMiddleware",  # Generate CSP nonce for each request
    "django.contrib.sessions.middleware.SessionMiddleware",  # Must be before CaptchaRequirementMiddleware
    "src.frontend.middleware.CaptchaRequirementMiddleware",  # Track failed attempts for CAPTCHA
    "django.middleware.locale.LocaleMiddleware",  # ✅ ТОЛЬКО ОДИН РАЗ! Должна быть ДО CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "src.api.middleware.OperationRunTrackingMiddleware",  # DB analytics for all operations
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "src.api.middleware.SecurityHeadersMiddleware",  # Add CSP and other security headers
]

# Add Prometheus middleware if available
try:
    import django_prometheus

    MIDDLEWARE.insert(0, "django_prometheus.middleware.PrometheusBeforeMiddleware")
    MIDDLEWARE.append("django_prometheus.middleware.PrometheusAfterMiddleware")
except ImportError:
    pass

ROOT_URLCONF = "utils_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "src.frontend.context_processors.csp_nonce",
                "src.frontend.context_processors.hreflang_links",
                "src.frontend.context_processors.site_urls",
                "src.frontend.context_processors.turnstile_site_key",
                "src.frontend.context_processors.js_settings",
                "src.frontend.context_processors.conversion_limits",
                "src.frontend.context_processors.payments_enabled",
                "src.frontend.context_processors.breadcrumbs",
                "src.frontend.context_processors.related_tools",
            ],
        },
    },
]

WSGI_APPLICATION = "utils_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support for PostgreSQL in production, SQLite for development
# In production, DATABASE_ENGINE must be explicitly set to "postgresql"
DATABASE_ENGINE = config("DATABASE_ENGINE", default="sqlite3")

# Security check: prevent SQLite in production
if not DEBUG and DATABASE_ENGINE == "sqlite3":
    raise ValueError(
        "SQLite cannot be used in production! "
        "Set DATABASE_ENGINE=postgresql in your environment variables."
    )

if DATABASE_ENGINE == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DATABASE_NAME", default="convertica_db"),
            "USER": config("DATABASE_USER", default="convertica_user"),
            "PASSWORD": config("DATABASE_PASSWORD", default=""),
            "HOST": config("DATABASE_HOST", default="localhost"),
            "PORT": config("DATABASE_PORT", default="5432"),
            "CONN_MAX_AGE": 300,  # Connection pooling: reuse for 5 min (reduces connection churn)
            "OPTIONS": {
                "connect_timeout": 10,
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Custom User Model
AUTH_USER_MODEL = "users.User"

# Django Allauth Configuration
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth account settings
ACCOUNT_ADAPTER = "src.users.account_adapter.CustomAccountAdapter"
# Use legacy settings for allauth 0.63.x compatibility (pinned in requirements.txt)
# These also work in newer versions (with deprecation warnings)
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Login using email (not username)
ACCOUNT_USERNAME_REQUIRED = False  # Don't require username
ACCOUNT_EMAIL_REQUIRED = True  # Email is required for registration
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Require email verification before login
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = (
    "/users/profile/"  # Redirect after email confirmation (logged in users)
)
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = (
    "/users/login/"  # Redirect after email confirmation (anonymous users)
)
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Auto-login after email confirmation

# Allauth social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "src.users.social_adapter.SocialAccountAdapter"
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True


# Login/Logout URLs
LOGIN_URL = "/users/login/"
LOGIN_REDIRECT_URL = "/users/profile/"
LOGOUT_REDIRECT_URL = "/users/login/"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
    ("pl", "Polski"),
    ("hi", "हिन्दी"),
    ("es", "Español"),
    ("id", "Bahasa Indonesia"),
    ("ar", "العربية"),
]

# Language detection settings
# LocaleMiddleware will automatically detect language from:
# 1. Session (if user selected language)
# 2. Cookie (django_language)
# 3. Accept-Language header from browser
# 4. Default LANGUAGE_CODE
TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Locale paths for translations
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = "/static/"

# Media files (user uploads, async temp files)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Use ManifestStaticFilesStorage for versioning (hash in filenames)
# This allows long-term caching (365 days) while automatically invalidating
# cache when files change (new hash = new filename)
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

# WhiteNoise configuration (alternative to Nginx for static files)
# Enable by setting USE_WHITENOISE=True in environment
USE_WHITENOISE = config("USE_WHITENOISE", default=False, cast=bool)

if USE_WHITENOISE:
    # Add WhiteNoise middleware (should be after SecurityMiddleware)
    if "whitenoise.middleware.WhiteNoiseMiddleware" not in MIDDLEWARE:
        # Insert after SecurityMiddleware
        security_index = MIDDLEWARE.index(
            "django.middleware.security.SecurityMiddleware"
        )
        MIDDLEWARE.insert(
            security_index + 1, "whitenoise.middleware.WhiteNoiseMiddleware"
        )

    # WhiteNoise settings for optimized static file serving
    # Use ManifestStaticFilesStorage for versioning
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

    # Cache static files for 1 year
    WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds

    # Enable compression
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh in development

# Admin Security Settings
# IP addresses allowed to access admin panel
# Load from environment variable (comma-separated), fallback to localhost
ADMIN_IP_WHITELIST = config("ADMIN_IP_WHITELIST", default="127.0.0.1,::1", cast=Csv())

# Admin URL path - change this to something unique!
# Load from environment variable, fallback to 'admin' for development
ADMIN_URL_PATH = config("ADMIN_URL_PATH", default="admin")

# Conversion API settings
MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50 MB
CONVERSION_TIMEOUT = 600  # 10 minutes (in seconds)
TEMP_DIR_PREFIX = "convertica_"

# ============================================================================
# CONVERSION LIMITS - All configurable via environment variables
# ============================================================================

# HTML to PDF character limits
HTML_TO_PDF_MAX_CHARS_FREE = config(
    "HTML_TO_PDF_MAX_CHARS_FREE", default=10000, cast=int
)
HTML_TO_PDF_MAX_CHARS_PREMIUM = config(
    "HTML_TO_PDF_MAX_CHARS_PREMIUM", default=500000, cast=int
)

# PDF page limits
MAX_PDF_PAGES_FREE = config("MAX_PDF_PAGES_FREE", default=30, cast=int)
MAX_PDF_PAGES_PREMIUM = config("MAX_PDF_PAGES_PREMIUM", default=200, cast=int)
MAX_PDF_PAGES_HEAVY_FREE = config("MAX_PDF_PAGES_HEAVY_FREE", default=30, cast=int)
MAX_PDF_PAGES_HEAVY_PREMIUM = config(
    "MAX_PDF_PAGES_HEAVY_PREMIUM", default=100, cast=int
)

# File size limits (in bytes)
MAX_FILE_SIZE_FREE = config(
    "MAX_FILE_SIZE_FREE", default=25 * 1024 * 1024, cast=int
)  # 25 MB
MAX_FILE_SIZE_PREMIUM = config(
    "MAX_FILE_SIZE_PREMIUM", default=200 * 1024 * 1024, cast=int
)  # 200 MB
MAX_FILE_SIZE_HEAVY_FREE = config(
    "MAX_FILE_SIZE_HEAVY_FREE", default=15 * 1024 * 1024, cast=int
)  # 15 MB
MAX_FILE_SIZE_HEAVY_PREMIUM = config(
    "MAX_FILE_SIZE_HEAVY_PREMIUM", default=100 * 1024 * 1024, cast=int
)  # 100 MB

# Batch processing limits
MAX_BATCH_FILES_FREE = config("MAX_BATCH_FILES_FREE", default=1, cast=int)
MAX_BATCH_FILES_PREMIUM = config("MAX_BATCH_FILES_PREMIUM", default=10, cast=int)

# Premium operation-specific page limits
# Override in .env as JSON: PREMIUM_PAGE_LIMITS={"pdf_to_word": 500, ...}
# These limits are per-operation maximums for premium users
PREMIUM_PAGE_LIMITS = {
    # Heavy conversions (CPU/memory intensive)
    "pdf_to_word": 300,
    "pdf_to_excel": 300,
    "pdf_to_ppt": 300,
    "pdf_to_html": 300,
    "word_to_pdf": 300,
    "excel_to_pdf": 300,
    "ppt_to_pdf": 300,
    # Image conversions
    "html_to_pdf": 150,
    "url_to_pdf": 150,
    "pdf_to_jpg": 150,
    # PDF organization (relatively fast)
    "compress_pdf": 400,
    "merge_pdf": 400,
    "split_pdf": 400,
    # Simple operations (very fast)
    "rotate_pdf": 700,
    "crop_pdf": 700,
    "organize_pdf": 700,
    "extract_pages": 700,
    "remove_pages": 700,
    "unlock_pdf": 700,
    "protect_pdf": 700,
    "add_watermark": 700,
    "add_page_numbers": 700,
}

# DPI limits for image conversion
DEFAULT_DPI = 300  # Default DPI for PDF to image conversion
MAX_DPI = 600  # Maximum DPI for PDF to image conversion
MIN_DPI = 72  # Minimum DPI for PDF to image conversion

# UI Settings
# Time in seconds before showing "patience message" during long conversions
PATIENCE_MESSAGE_DELAY = config("PATIENCE_MESSAGE_DELAY", default=60, cast=int)
# Polling interval for async task status (milliseconds)
ASYNC_POLL_INTERVAL = config("ASYNC_POLL_INTERVAL", default=2500, cast=int)

# Stripe Payment Settings
PAYMENTS_ENABLED = config("PAYMENTS_ENABLED", default="True", cast=bool)
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="pk_test_...")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

# Stripe Webhook IP Whitelist
# https://stripe.com/docs/ips - these are Stripe's webhook IP addresses
# Set STRIPE_WEBHOOK_IP_WHITELIST_ENABLED=False to disable IP checking (signature is still verified)
STRIPE_WEBHOOK_IP_WHITELIST_ENABLED = config(
    "STRIPE_WEBHOOK_IP_WHITELIST_ENABLED", default=True, cast=bool
)
# Stripe webhook IPs (updated Jan 2024, check https://stripe.com/docs/ips for latest)
STRIPE_WEBHOOK_IPS = [
    # Stripe webhook source IPs
    "3.18.12.63",
    "3.130.192.231",
    "13.235.14.237",
    "13.235.122.149",
    "18.211.135.69",
    "35.154.171.200",
    "52.15.183.38",
    "54.88.130.119",
    "54.88.130.237",
    "54.187.174.169",
    "54.187.205.235",
    "54.187.216.72",
    # Allow localhost for testing
    "127.0.0.1",
    "::1",
]
STRIPE_SUCCESS_URL = config("STRIPE_SUCCESS_URL", default="/payments/success/")
STRIPE_CANCEL_URL = config("STRIPE_CANCEL_URL", default="/payments/cancel/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "structured": {
            "format": "{levelname} {asctime} {name} [{module}] {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "suppress_disallowed_host": {
            "()": "src.api.log_filters.SuppressDisallowedHostFilter",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "structured",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "logs" / "convertica.log",
            "when": "W0",
            "interval": 1,
            "backupCount": 8,
            "formatter": "structured",
            "encoding": "utf-8",  # Support UTF-8 encoding for international characters
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "logs" / "errors.log",
            "when": "W0",
            "interval": 1,
            "backupCount": 8,
            "formatter": "verbose",
            "encoding": "utf-8",  # Support UTF-8 encoding for international characters
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["error_file", "console"],
            "level": "ERROR",
            "propagate": False,
        },
        "src.api": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,  # Avoid duplicate console logs (already handled here)
        },
        "src": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,  # Avoid duplicate console logs (already handled here)
        },
        # Send ERROR and above to Sentry (via root logger)
        "sentry_sdk": {
            "level": "WARNING",
            "handlers": ["console"],
            "propagate": False,
        },
        # Filter out Gunicorn access logs completely - these are just HTTP request logs, not errors
        "gunicorn.access": {
            "handlers": [],  # No handlers - completely disable
            "level": "CRITICAL",  # Highest level to effectively disable
            "propagate": False,  # Don't propagate to root logger
        },
        # Gunicorn error logs - filter noisy ones in before_send
        "gunicorn.error": {
            "handlers": ["console", "error_file"],
            "level": "WARNING",  # Only WARNING and above (ERROR, CRITICAL)
            "propagate": False,  # Don't propagate to root logger
            "filters": ["suppress_disallowed_host"],  # Filter DisallowedHost errors
        },
        # Django security logs - suppress DisallowedHost (bot scanners)
        "django.security.DisallowedHost": {
            "handlers": [],  # Completely suppress - these are just bot scanners
            "level": "CRITICAL",
            "propagate": False,
        },
        "allauth": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "allauth.account": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "allauth.socialaccount": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",  # ERROR and above will be sent to Sentry via enable_logs=True
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / "logs"
if not logs_dir.exists():
    os.makedirs(logs_dir, exist_ok=True)

# Security Settings for Production
# These settings are automatically enabled when DEBUG=False
# You can also override them via environment variables

# HTTPS Settings (only in production)
if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
    CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"  # Protection against clickjacking
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# Force HTTP for local development
USE_HTTP = DEBUG
FORCE_HTTP = DEBUG


# Override the site framework to use our custom domain


# CSRF Trusted Origins - required for CSRF to work with HTTPS
# Django 4.0+ requires explicit list of trusted origins for CSRF
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://convertica.net,https://www.convertica.net",
    cast=Csv(),
)
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
# Cache Configuration
# Using Redis for caching and session storage
try:
    import django_redis

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": config("REDIS_URL", default="redis://127.0.0.1:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "IGNORE_EXCEPTIONS": True,  # Don't fail if Redis is down
            },
            "KEY_PREFIX": "convertica",
            "TIMEOUT": 3600,  # Default timeout: 1 hour (cache cleared on deploy)
        }
    }
except ImportError:
    # Fallback to file-based cache if django-redis is not installed
    # This provides a shared cache backend for django-ratelimit
    import os

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": os.path.join(BASE_DIR, "cache"),
        }
    }

# Session backend using Redis (if available)
try:
    import django_redis

    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
except ImportError:
    # Fallback to database sessions if django-redis is not installed
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Enhanced session security
SESSION_COOKIE_AGE = 86400  # 24 hours session timeout
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_SAVE_EVERY_REQUEST = (
    False  # Only save session when modified (prevents memory leak)
)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session after browser close

# Celery Configuration
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

# Celery Beat Schedule (periodic tasks)
# NOTE: This configuration takes precedence over celery.py configuration
CELERY_BEAT_SCHEDULE = {
    # Clean up temp files every hour (safety net)
    "cleanup-temp-files-hourly": {
        "task": "maintenance.cleanup_temp_files",
        "schedule": 3600,  # Every hour
    },
    # Clean up async temp files every 30 minutes
    "cleanup-async-temp-files": {
        "task": "maintenance.cleanup_async_temp_files",
        "schedule": 1800,  # Every 30 minutes
        "kwargs": {"max_age_seconds": 3600},  # Clean files older than 1 hour
    },
    # Memory cleanup every 15 minutes (for 4GB servers)
    "memory-cleanup": {
        "task": "maintenance.memory_cleanup",
        "schedule": 900,  # Every 15 minutes
    },
    # Update subscriptions daily
    "update-subscription-daily": {
        "task": "maintenance.update_subscription_daily",
        "schedule": 86400,  # Every 24 hours
    },
    # Mark stuck operations as abandoned (but don't delete them)
    "cleanup-stuck-operations": {
        "task": "maintenance.cleanup_stuck_operations",
        "schedule": 3600,  # Every hour
        "kwargs": {
            "max_age_hours": 24
        },  # Mark as abandoned after 24 hours (not 1 hour!)
    },
    # Delete unverified accounts older than 30 days (runs daily)
    "delete-unverified-accounts-daily": {
        "task": "user_cleanup.delete_unverified_accounts",
        "schedule": 86400,  # Every 24 hours
    },
    # Retry failed Stripe webhooks every hour
    "retry-failed-webhooks": {
        "task": "maintenance.retry_failed_webhooks",
        "schedule": 3600,  # Every hour
        "kwargs": {
            "max_age_hours": 24,  # Only retry events from last 24 hours
            "max_retries": 3,  # Maximum 3 retry attempts
        },
    },
    # ⚠️ DISABLED: cleanup-old-operations - Keep all operation data permanently
    # If you need to cleanup old data, run manually:
    #   docker compose exec web python manage.py shell -c "from src.tasks.maintenance import cleanup_old_operations; cleanup_old_operations(retention_days=730)"
    # "cleanup-old-operations": {
    #     "task": "maintenance.cleanup_old_operations",
    #     "schedule": 86400,  # Every 24 hours
    #     "kwargs": {"retention_days": 730},  # Keep operations for 2 years (was 365)
    # },
}

# Rate Limiting Configuration
RATELIMIT_ENABLE = config("RATELIMIT_ENABLE", default=True, cast=bool)
RATELIMIT_USE_CACHE = "default"  # Use Redis cache for rate limiting

# API Rate Limits (requests per minute)
API_RATE_LIMIT = {
    "default": "100/m",  # 100 requests per minute
    "pdf_conversion": "20/m",  # 20 PDF conversions per minute
    "file_upload": "30/m",  # 30 file uploads per minute
}

# Email Configuration
# https://docs.djangoproject.com/en/5.2/topics/email/
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default=(
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = config("EMAIL_HOST", default="localhost")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@convertica.net")
CONTACT_EMAIL = config("CONTACT_EMAIL", default="info@convertica.net")

# Cloudflare Turnstile Configuration
TURNSTILE_SITE_KEY = config("TURNSTILE_SITE_KEY", default="")
TURNSTILE_SECRET_KEY = config("TURNSTILE_SECRET_KEY", default="")

# Telegram Bot Configuration
CONTACT_TELEGRAM_ENABLED = config("CONTACT_TELEGRAM_ENABLED", default="True")

# Subscription Pricing Configuration
SUBSCRIPTION_PRICING = {
    "daily": {
        "price": config("DAILY_PRICE", default="1.00", cast=float),
        "duration_days": 1,
        "name": "Daily Hero Access",
    },
    "monthly": {
        "price": config("MONTHLY_PRICE", default="6.00", cast=float),
        "duration_days": 30,
        "name": "Monthly Hero Access",
    },
}

# Web Push Notifications (VAPID Keys)
VAPID_PRIVATE_KEY = config("VAPID_PRIVATE_KEY", default="").replace("\\n", "\n")
VAPID_PUBLIC_KEY = config("VAPID_PUBLIC_KEY", default="")
VAPID_CLAIMS = {
    "sub": config("VAPID_CLAIMS_SUB", default="mailto:admin@convertica.net")
}

SUBSCRIPTION_PRICING.update(
    {
        "yearly": {
            "price": config("YEARLY_PRICE", default="52.00", cast=float),
            "duration_days": 365,
            "name": "Yearly Hero Access",
        },
    }
)

TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN", default="", cast=str)
TELEGRAM_CHAT_ID = config("TELEGRAM_CHAT_ID", default="", cast=str)


# Django Channels Configuration (WebSocket support)
try:
    import channels

    # ASGI application for Channels
    ASGI_APPLICATION = "utils_site.asgi.application"

    # Channel layer configuration (Redis backend recommended for production)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [config("REDIS_URL", default="redis://127.0.0.1:6379/2")],
                "capacity": 1500,
                "expiry": 10,
            },
        },
    }

    # Fallback to in-memory channel layer for development if Redis not available
    try:
        import channels_redis
    except ImportError:
        CHANNEL_LAYERS = {
            "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
        }
except ImportError:
    # Channels not installed, skip configuration
    pass

# Custom error handlers (defined in utils_site.urls)
# Django will automatically use handler404, handler500, etc. from ROOT_URLCONF
# These are defined in utils_site/urls.py

# ============================================
# IndexNow Configuration
# ============================================
# IndexNow is a protocol for instant search engine indexing
# Supported: Bing, Yandex, Seznam (Google is testing)
INDEXNOW_ENABLED = config("INDEXNOW_ENABLED", default=False, cast=bool)
INDEXNOW_KEY = config("INDEXNOW_KEY", default="")

# Site base URL for IndexNow (fallback if not set elsewhere)
if not hasattr(locals(), "SITE_BASE_URL"):
    SITE_BASE_URL = "https://convertica.net"
