# Generated by Django 5.2.8 on 2025-12-19 15:25

import src.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", src.users.models.UserManager()),
            ],
        ),
    ]
