# Generated by Django 5.2.8 on 2025-12-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscriptionplan_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Payment Method"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Processed At"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Transaction ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="consecutive_subscription_days",
            field=models.IntegerField(
                default=0, verbose_name="Consecutive Subscription Days"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Subscription End Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Subscription Start Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_subscription_days",
            field=models.IntegerField(
                default=0, verbose_name="Total Subscription Days"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "-created_at"], name="users_payme_user_id_e0ed8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-created_at"], name="users_payme_status_b9b555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_id"], name="users_payme_payment_0485c0_idx"
            ),
        ),
    ]
