# Generated by Django 5.2.8 on 2025-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_method_payment_processed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_as_hero",
            field=models.BooleanField(default=False, verbose_name="Display as Hero"),
        ),
    ]
