# Generated by Django 5.2.8 on 2025-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_subscriptionplan_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("livemode", models.BooleanField(default=False)),
                ("processing", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["event_id"], name="users_stripe_event_id_idx"),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="users_stripe_event_type_created_idx",
                    ),
                    models.Index(
                        fields=["processed_at"],
                        name="users_stripe_event_processed_at_idx",
                    ),
                ],
            },
        ),
    ]
