# Generated by Django 5.2.8 on 2025-12-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_stripewebhookevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversion_type", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "started"),
                            ("queued", "queued"),
                            ("running", "running"),
                            ("success", "success"),
                            ("error", "error"),
                            ("cancel_requested", "cancel_requested"),
                            ("cancelled", "cancelled"),
                            ("abandoned", "abandoned"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("task_id", models.CharField(blank=True, max_length=64)),
                ("input_size", models.BigIntegerField(blank=True, null=True)),
                ("output_size", models.BigIntegerField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("queue_wait_ms", models.IntegerField(blank=True, null=True)),
                ("error_type", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("remote_addr", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.TextField(blank=True)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["conversion_type", "-created_at"],
                        name="users_oprun_conv_created_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="users_oprun_status_created_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_oprun_user_created_idx",
                    ),
                    models.Index(fields=["task_id"], name="users_oprun_task_id_idx"),
                    models.Index(
                        fields=["request_id"], name="users_oprun_request_id_idx"
                    ),
                    models.Index(
                        fields=["is_premium", "conversion_type", "-created_at"],
                        name="users_oprun_prem_conv_created_idx",
                    ),
                ],
            },
        ),
    ]
