# Generated by Django 5.2.8 on 2026-01-04 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_composite_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_convers_d70162_idx",
            old_name="users_oprun_conv_created_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_status_117423_idx",
            old_name="users_oprun_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_user_id_136365_idx",
            old_name="users_oprun_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_task_id_ce08c4_idx",
            old_name="users_oprun_task_id_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_request_7dd5ee_idx",
            old_name="users_oprun_request_id_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_is_prem_4170d1_idx",
            old_name="users_oprun_prem_conv_created_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_user_id_44f659_idx",
            old_name="users_opera_user_id_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_is_prem_cc29d0_idx",
            old_name="users_opera_is_prem_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="operationrun",
            new_name="users_opera_convers_582843_idx",
            old_name="users_opera_conv_ty_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="stripewebhookevent",
            new_name="users_strip_event_i_20fac7_idx",
            old_name="users_stripe_event_id_idx",
        ),
        migrations.RenameIndex(
            model_name="stripewebhookevent",
            new_name="users_strip_event_t_abb95e_idx",
            old_name="users_stripe_event_type_created_idx",
        ),
        migrations.RenameIndex(
            model_name="stripewebhookevent",
            new_name="users_strip_process_3e3129_idx",
            old_name="users_stripe_event_processed_at_idx",
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
