# Generated by Django 5.2.8 on 2026-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0010_rename_users_oprun_conv_created_idx_users_opera_convers_d70162_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Premium"
            ),
        ),
    ]
