# Generated by Django 5.2.8 on 2026-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_is_premium_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Runtime Setting",
                "verbose_name_plural": "Runtime Settings",
                "ordering": ["key"],
            },
        ),
    ]
