# Generated by Django 5.2.12 on 2026-05-02 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_provider_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeWebhookEvent',
        ),
    ]
