# Generated by Django 5.2.8 on 2026-05-19 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_rename_subscription_related"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="User-set label", max_length=64)),
                ("prefix", models.CharField(db_index=True, max_length=20, unique=True)),
                ("key_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "scope",
                    models.JSONField(default=list, help_text='Tool slugs or ["*"]'),
                ),
                ("usage_this_month", models.PositiveIntegerField(default=0)),
                ("usage_reset_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_apike_user_id_8f476f_idx",
                    )
                ],
            },
        ),
    ]
