# Generated by Django 5.2.8 on 2026-05-19 14:12

from django.db import migrations, models


def _set_default_quotas(apps, schema_editor):
    SubscriptionPlan = apps.get_model("users", "SubscriptionPlan")
    # Slugs are stable across runs; created by the
    # create_subscription_plans management command.
    DEFAULTS = {
        "monthly-hero": 1_000,
        "yearly-hero": 10_000,
        "lifetime-hero": 10_000,
    }
    for slug, quota in DEFAULTS.items():
        SubscriptionPlan.objects.filter(slug=slug).update(api_quota_per_month=quota)


def _noop_reverse(apps, schema_editor):
    # Reverse path: field is dropped by the AddField reverse, so quota
    # rows disappear with it. No data to restore.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="api_quota_per_month",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Monthly /api/v1 call quota for subscribers of this plan. 0 = no API access.",
            ),
        ),
        migrations.RunPython(_set_default_quotas, _noop_reverse),
    ]
