# Generated by Django 5.2.8 on 2026-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_subscriptionplan_api_quota_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Per-user HMAC secret for signing outbound webhook callbacks.",
                max_length=64,
            ),
        ),
    ]
