# Generated by Django 5.2.8 on 2026-06-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_fix_admin_log_user_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationrun",
            name="peak_rss_mb",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
