# Generated by Django 5.2.8 on 2026-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_user_preferred_language_welcome_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageViewDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("path", models.CharField(max_length=255)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Page view (daily)",
                "verbose_name_plural": "Page views (daily)",
                "indexes": [
                    models.Index(fields=["-date"], name="users_pagev_date_6af2ef_idx")
                ],
                "unique_together": {("date", "path")},
            },
        ),
    ]
