# Generated by Django 5.2.8 on 2026-08-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_fill_site_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="paddle_price_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="paddle_product_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
