# Generated by Django 5.2.8 on 2026-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_add_polar_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkflowset",
            name="boards",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
