# Generated by Django 5.2.8 on 2026-09-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_userworkflowset_boards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lemonsqueezy", "Lemon Squeezy"),
                    ("paddle", "Paddle"),
                    ("polar", "Polar"),
                ],
                default="",
                editable=False,
                max_length=20,
            ),
        ),
    ]
