# Generated by Django 5.2.8 on 2025-12-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Name (Russian)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Title (Russian)')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Content (Russian)')),
                ('excerpt_en', models.TextField(blank=True, max_length=500, verbose_name='Excerpt (English)')),
                ('excerpt_ru', models.TextField(blank=True, max_length=500, verbose_name='Excerpt (Russian)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (English)')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (Russian)')),
                ('meta_description_en', models.TextField(blank=True, max_length=500, verbose_name='Meta Description (English)')),
                ('meta_description_ru', models.TextField(blank=True, max_length=500, verbose_name='Meta Description (Russian)')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords (English)')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords (Russian)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Featured Image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.articlecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_articl_status_8b18ca_idx'), models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'), models.Index(fields=['category'], name='blog_articl_categor_5bebf3_idx')],
            },
        ),
    ]
