# Generated by Django 5.2.8 on 2025-12-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_jsonfield_translations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="excerpt_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="meta_description_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="meta_keywords_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="meta_title_ru",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="articlecategory",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="articlecategory",
            name="name_ru",
        ),
    ]
