# Generated by Django 5.2.12 on 2026-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_fix_internal_links_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='relevant_tool',
            field=models.CharField(blank=True, choices=[('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('pdf_to_jpg', 'PDF to JPG'), ('jpg_to_pdf', 'JPG to PDF'), ('pdf_to_excel', 'PDF to Excel'), ('merge_pdf', 'Merge PDF'), ('split_pdf', 'Split PDF'), ('compress_pdf', 'Compress PDF'), ('rotate_pdf', 'Rotate PDF'), ('crop_pdf', 'Crop PDF'), ('add_watermark', 'Add Watermark'), ('protect_pdf', 'Protect PDF'), ('unlock_pdf', 'Unlock PDF'), ('organize_pdf', 'Organize PDF'), ('extract_pages', 'Extract Pages'), ('remove_pages', 'Remove Pages'), ('add_page_numbers', 'Add Page Numbers'), ('protect_zip', 'Password Protect ZIP'), ('unlock_zip', 'Unlock ZIP'), ('all_tools', 'All Tools')], help_text='Select the most relevant tool for this article', max_length=50, null=True, verbose_name='Relevant Tool'),
        ),
    ]
