# Generated by Django 5.2.8 on 2026-06-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_relevant_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.CharField(
                blank=True,
                help_text="Static-relative path under STATIC_URL, e.g. 'blog/images/cover-foo.jpg'. Preferred over Featured Image; ships with the repo.",
                max_length=255,
                null=True,
                verbose_name="Cover Image (static path)",
            ),
        ),
    ]
